server:
  port: 8082
spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5434/food-db}
    username: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD:root}
  flyway:
    enabled: true
    validate-on-migrate: true
    locations: classpath:db/migration
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
    show-sql: true
